theme = "tokyonight"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"
rulers = [80]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal."space"]
o = "file_picker_in_current_buffer_directory"
W = ":wa"

[editor.cursor-shape]
insert = "bar"

