theme = "tokyonight"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[keys.normal]
C-s = ":w" 
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"

