[language-server.emmet-lsp]
command = "emmet-language-server"
args = ['--stdio']

[language-server.eslint]
command = "vscode-eslint-language-server"
args = ['--stdio']

[language-server.solargraph.config]
diagnostics = true
formatting = false

[language-server.eslint.config]
codeActionOnSave = { mode = "all", "source.fixAll.eslint" = true}
experimental = {}
format = {enable = true}
nodePath = ""
onIgnoredFiles = "off"
packageManager = "yarn"
problems = { shortenToSingleLine = false}
quiet = false
rulesCustomizations = []
run = "onType"
validate = "on"

[language-server.eslint.config.codeAction]
disableRuleAction = {enable = true, location = "separateLine"}
showDocumentation = { enable = false}

[[language]]
language-servers = ['eslint','typescript-language-server', 'emmet-lsp']
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
name = "typescript"
auto-format = true

[[language]]
language-servers = ['eslint', 'typescript-language-server', 'emmet-lsp']
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
name = "javascript"
auto-format = true

[[language]]
language-servers = ['emmet-lsp', 'eslint', 'typescript-language-server']
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
name = "jsx"
auto-format = true

[[language]]
language-servers = ['emmet-lsp', 'eslint', 'typescript-language-server']
formatter = { command = "prettier", args = [ "--parser", "typescript" ] }
name = "tsx"
auto-format = true

[[language]]
name = "ruby"
formatter = { command = "bundle", args = ["exec", "rubocop", "--stdin", "foo.rb", "-a", "--stderr", "--fail-level", "fatal"] }
auto-format = true
